version: '2'
services:
    wmall-app:
        image: wmall
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@wmall-oracle:1521:wmall
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8103:8103
